# Creates a new EC2 instance for the Faucet server.
# This config expects an Elastic IP to have been defined at 18.210.76.115
---
- name: Create an EC2 instance
  hosts: local
  become: False
  tasks:
    - name: Launch Faucet Instance
      ec2:
        id: faucet-server-v1
        key_name: faucet-key-pair
        image: ami-14c5486b
        group_id: sg-08586a68856e461cb
        instance_type: t2.micro
        region: us-east-1
        state: present
      register: ec2
    - name: Associate Elastic IP
      ec2_eip:
        allow_reassociation: true
        device_id: "{{ ec2.instance_ids[0] }}"
        public_ip: 18.210.76.115
        region: us-east-1

- name: Setup the Faucet server for Docker
  hosts: faucet-server
  tasks:
    - name: Update server
      become: yes
      yum:
        name: '*'
        state: latest

    - name: Ensure pip is latest
      pip:
        name: pip
        state: latest

    - name: Install requests
      pip:
        name: requests
        state: present

    - name: Install Docker
      become: yes
      yum:
        name: docker
        state: present

    - name: "remove chardet / distutils prior to installing docker-compose"
      command: rm /usr/lib/python2.7/dist-packages/chardet-2.0.1.egg-info && rm -rf /usr/lib/python2.7/dist-packages/chardet
      become: true

    - name: Install docker compose
      command: pip install docker-compose
      become: true
      tags:
        - docker

    - name: Start Docker Service
      become: yes
      service:
        name: docker
        state: started

    - name: Add ec2-user to docker group
      become: yes
      user:
        name: ec2-user
        groups: docker
        append: yes
