version: "3"
services:
  redis:
    build: './redis'
    volumes:
      - /docker/var/log/redis:/var/log/redis
      - /docker/usr/local/var/db/redis:/usr/local/var/db/redis
  express-server:
    env_file:
      - ../faucet-service.env
    build: './express-server'
    ports:
      - 8080:8080
    links:
      - redis
      - nginx
  nginx:
    build: './nginx-custom'
    volumes:
      - /docker/var/log/nginx:/var/log/nginx
      - /docker/etc/nginx/conf.d:/etc/nginx/conf.d/faucet-service
    ports:
      - 80:80
