version: "3"
services:
  # faucet:
  #   env_file:
  #     - ../faucet-service.env
  #   build: './faucet'
  #   volumes:
  #     - "/docker/var/faucet/export:/export"
  #     - "/docker/var/faucet/data:/data/faucet"
  #   ports:
  #     - 8080:80
  nginx:
    build: './nginx-custom'
    volumes:
      - /docker/var/log/nginx:/var/log/nginx
      - /docker/etc/nginx/conf.d:/etc/nginx/conf.d/faucet-service
    ports:
      - 80:80
